### ISSUE TITLE
Improve docs for ocprometheus

### ISSUE THREAD

**Issue by RichiH** [aristanetworks/goarista#16]
@fhibler

**Comment by yeled** [comment]
@fhibler

**Comment by topine** [comment]
+ 1

**Comment by yeled** [comment]
we missed a year.

**Comment by noredistribution** [comment]
added reference to the EOS Central article which contains an end to end demo with several examples as part of https://github.com/aristanetworks/goarista/commit/51f8fd3f0e89c9906250140e1841a542fbb7d9ad
