### ISSUE TITLE
collecting gRPC and native UDP telemetry data 

### ISSUE THREAD

**Issue by littlespace** [aristanetworks/goarista#24]
Hi,

I just wanted to know how can I collect gRPC and native UDP telemetry data  with Telegraf?

Thanks,

**Comment by wladh** [comment]
We don't currently have a plugin for Telegraf. However, depending on which backend you're using for Telegraf, we might have a plugin that streams to that backend (eg, if you're using InfluxDB, you can use `octsdb` to send the data to Influx via its OpenTSDB protocol).

**Comment by littlespace** [comment]
I am using InfluxDB.  do you have some sample for the config?

**Comment by littlespace** [comment]
does Arista also support the UDP streaming as well?

**Comment by wladh** [comment]
You can have a look at the sample configs here:
https://github.com/aristanetworks/goarista/tree/master/cmd/octsdb
`octsdb` supports UDP streaming to InfluxDB.
