### ISSUE TITLE
ocprometheus returns error : failed to subscribe 

### ISSUE THREAD

**Issue by sk1988** [aristanetworks/goarista#26]
I am trying to setup ocprometheus/gnmi on Arista 7060CX2 device using Arista version 4.20.6F.

Below is the configuration on my Arista device:

qa-001#sh run | sec management
!
management api gnmi
   transport grpc def
      vrf MGMT
!

qa-001#sh management api gnmi 
Enabled:            Yes
Server:             running on port 6030, in MGMT VRF
SSL Profile:        none
qa-001#

qa-001#show processes | i Open
 4273  2.4  1.8 ?        Sl   09:10:24 00:32:19 /usr/bin/OpenConfig --agenttitle=OpenConfig --demuxerOpts=3325211945484,3325211570139,tbl://sysdb/+n,Sysdb (pid:1523) --sysdbfd=7
17414  0.0  0.0 pts/4    Ss+  07:30:28 00:00:00 grep -aEe Open
qa-001#

I am on go version go1.10.1 linux/amd64 and Centos 7.2.

[root@qa0801 ~]#ocprometheus -addr qa-001.mgmt:6030 -config sampleconfig_above_4.20.yml
F1024 07:39:39.609355   70578 main.go:90] rpc error: code = Unauthenticated desc = Authentication failed

[root@qa0801 ~]# ocprometheus -addr qa-001.mgmt:6030 -config sampleconfig_above_4.20.yml -username xxxxx -password xxxxx
F1024 06:51:19.050065   39284 main.go:90] rpc error: code = InvalidArgument desc = failed to subscribe to /Sysdb/environment/archer/cooling/status: path invalid: failed to access node "Sysdb" in node ""

[root@qa0801 ~]# ocprometheus -addr qa-001.mgmt:6030 -config sampleconfig_above_4.20.yml -username xxxxx -password xxxxx -subscribe /Sysdb
F1024 06:58:25.154923   43467 main.go:90] rpc error: code = InvalidArgument desc = failed to subscribe to /Sysdb: path invalid: failed to access node "Sysdb" in node ""
[root@qa0801 ~]#

Am I hitting a bug or did I miss some piece of configuration?  Could you please assist?

**Comment by wladh** [comment]
It seems that you're trying to subscribe to internal models (things starting with /Sysdb or /Smash) via openconfig. That's not supported. In order to access the internal models you need to run TerminAttr. Otherwise, if you're running OpenConfig, you can try to subscribe to openconfig paths.
