### ISSUE TITLE
gNMI build fails

### ISSUE THREAD

**Issue by fowie** [aristanetworks/goarista#28]
New Go installation: go version go1.11.1 windows/amd64

C:\%GOPATH%>go get github.com/aristanetworks/goarista/cmd/gnmi
# github.com/aristanetworks/goarista/netns
src\github.com\aristanetworks\goarista\netns\netns.go:35:17: undefined: getNs
src\github.com\aristanetworks\goarista\netns\netns.go:39:8: undefined: setNs
src\github.com\aristanetworks\goarista\netns\netns_110.go:34:19: undefined: getNs
src\github.com\aristanetworks\goarista\netns\netns_110.go:54:11: undefined: setNs

**Comment by aaronbee** [comment]
It looks to me like you are on a Windows machine. Is that correct?

Unfortunately, it looks like you can only build gNMI for linux or macOS. Let me see if I can restructure the code so that we can enable building a Windows binary.

**Comment by aaronbee** [comment]
Sorry, you did mention your platform is windows/amd64.

**Comment by aaronbee** [comment]
@fowie This should be fixed now. Thanks for the issue! https://github.com/aristanetworks/goarista/commit/5bb443fba8e05f4a819301a63af91fe3cbadcc17
