### ISSUE TITLE
GNMI calls fails with below error

### ISSUE THREAD

**Issue by SVenky** [aristanetworks/goarista#31]
gnmi -addr 172.18.0.4 --username admin --password admin get origin="/" /n
etwork-instance[name=’default’]/
F0218 21:35:04.518261      88 main.go:114] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

gnmi --addr 172.18.0.4 --mode stream --username admin --password admin sub
scribe origin="/" /network-instance[name=’default’]/
F0218 21:34:24.533781      80 main.go:141] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

Any idea what is going wrong? Same if I use gnmi_cli of open config things work.

**Comment by aaronbee** [comment]
That error means that you have a network issue connecting to the target. Do you need to include a port number in you address argument?
