### ISSUE TITLE
goprometheus to veos ?

### ISSUE THREAD

**Issue by bodleytunes** [aristanetworks/goarista#32]
Is it possible to test basic telemetry features such as bandwidth with vEOS?

I'm getting a timeout error trying to connect to the management1 interface, wireshark shows syn but no syn ack coming back from the switch.  All default vrf.  Also can see the openconfig service running.

`~/go/bin# ./ocprometheus -config /etc/arista/config.yml -addr 10.224.122.80:6030
F0219 14:44:23.665902   11331 main.go:90] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.224.122.80:6030: connect: connection timed out"
`

**Comment by 7AC** [comment]
Do you have OpenConfig started in vEOS and is port 6030 reachable from where you're running ocprometheus?

**Comment by bodleytunes** [comment]
Think so, let me sanity check...

**Comment by bodleytunes** [comment]
![image](https://user-images.githubusercontent.com/619239/53086080-4b39e880-34fc-11e9-9b51-84f93c9a8ba8.png)
![image](https://user-images.githubusercontent.com/619239/53086093-5260f680-34fc-11e9-9384-faece2138402.png)

**Comment by bodleytunes** [comment]
![image](https://user-images.githubusercontent.com/619239/53086933-f39c7c80-34fd-11e9-993d-fa4942db7ce6.png)
![image](https://user-images.githubusercontent.com/619239/53087017-2181c100-34fe-11e9-9a50-292a9783c4c3.png)
Testing ping for ip reachability from VM hosting ocprometheus and then finally testing the command itself and not getting a syn ack.
![ocprom](https://user-images.githubusercontent.com/619239/53087273-9d7c0900-34fe-11e9-92fc-e7ca22aeb27a.gif)

**Comment by bodleytunes** [comment]
Also tried natting ocprometheus traffic on egress to the gateway ip just in case it was some reverse path / routing issue.   Same thing. :(

**Comment by bodleytunes** [comment]
Could it be that it doesn't work with the management1 interface and I have to use one of the main interfaces?

**Comment by bodleytunes** [comment]
![image](https://user-images.githubusercontent.com/619239/53088608-29dbfb00-3502-11e9-8eff-a6769c300ca7.png)
![image](https://user-images.githubusercontent.com/619239/53088636-37918080-3502-11e9-8593-cb0e1381ee64.png)

**Comment by bodleytunes** [comment]
iptables was blocking

**Comment by bodleytunes** [comment]
now I'm getting authentication failed

**Comment by bodleytunes** [comment]
sudo iptables -A INPUT -p tcp --dport 6030 -j ACCEPT

**Comment by bodleytunes** [comment]
bit further now, think its looking for an invalid sensor
F0220 11:34:08.443129   21913 main.go:90] rpc error: code = InvalidArgument desc = failed to subscribe to /Smash/counters/ethIntf: path invalid: failed to access node "Smash" in node ""

**Comment by Jochem22** [comment]
Try these examples:

https://github.com/aristanetworks/goarista/blob/master/cmd/octsdb/sampleconfig4.20.json

**Comment by bodleytunes** [comment]
can this be done from the cli as I ran raw iptables commands ?

**Comment by bodleytunes** [comment]
thats the sample json config I'm using currently.

Is there a command to list the available sensors to subscribe to on the veos itself so I'm not subsribing to invalid ones?

**Comment by Jochem22** [comment]
You can copy the default control-plane-acl and create a new one. Config the new acl on the management interface.

show ip access-lists
IP Access List default-control-plane-acl [readonly]
        statistics per-entry
        10 permit icmp any any [match 68406 packets, 0:03:58 ago]
        20 permit ip any any tracked [match 224753306 packets, 0:00:00 ago]
        30 permit udp any any eq bfd ttl eq 255
        40 permit udp any any eq bfd-echo ttl eq 254
        50 permit udp any any eq multihop-bfd
        60 permit udp any any eq micro-bfd
        70 permit ospf any any
        80 permit tcp any any eq ssh telnet www snmp bgp https msdp ldp [match 177458 packets, 0:00:28 ago]
        90 permit udp any any eq bootps bootpc snmp rip ntp ldp [match 238049 packets, 0:16:48 ago]
        100 permit tcp any any eq mlag ttl eq 255
        110 permit udp any any eq mlag ttl eq 255
        120 permit vrrp any any
        130 permit ahp any any
        140 permit pim any any
        150 permit igmp any any
        160 permit tcp any any range 5900 5910 [match 7392 packets, 3:10:18 ago]
        170 permit tcp any any range 50000 50100 [match 3467 packets, 0:57:38 ago]
        180 permit udp any any range 51000 51100 [match 2 packets, 75 days, 0:01:45 ago]
        190 permit tcp any any eq cvx-license [match 1050 packets, 0:03:48 ago]
        200 permit tcp any any eq nat ttl eq 255
        210 permit tcp any eq bgp any [match 2 packets, 17 days, 14:31:36 ago]

**Comment by Jochem22** [comment]
> thats the sample json config I'm using currently.
> 
> Is there a command to list the available sensors to subscribe to on the veos itself so I'm not subscribing to invalid ones?

I dont know how it works on newer versions of Arista but i use octsdb with the sample4.20.config and we are running TerminAttr on the switch. I dont know how to make it work with openconfig. 

You could try to subscribe to /sysdb/

**Comment by bodleytunes** [comment]
ok cheers, this is veos though so its all virtual.  I'm assuming a lot of the sensors will be invalid as will be related to physical hardware.

**Comment by aaronbee** [comment]
Using [gnmi](https://github.com/aristanetworks/goarista/tree/master/cmd/gnmi) you can discover all available data by subscribing to `/`.

```gnmi [options] subscribe /```

**Comment by bodleytunes** [comment]
thanks will give it a try
