### ISSUE TITLE
GNMI - Unable to subscribe to use stream_mode with sample_interval 

### ISSUE THREAD

**Issue by stangedas** [aristanetworks/goarista#36]
I am trying to use gnmi to enable -stream_mode sample and set a sample_interval of 1 min when using subscribe mode. I get below error
root@jumphost:~# gnmi -addr 10.xx.xx.xx:5909 -username user -password password -mode stream -stream_mode sample -sample_interval 1m subscribe '/components/component[name=PowerSupply1]/properties/'
F0502 14:56:40.145280    6775 main.go:141] rpc error: code = Unimplemented desc = only TARGET_DEFINED Subscription mode supported.

Am i using the wrong flags?

**Comment by aaronbee** [comment]
SAMPLE stream mode support was added to Arista's EOS in 4.21.3F.

**Comment by stangedas** [comment]
Thank you Aaron we updated our EOS to latest available and the feature is working as expected.
