### ISSUE TITLE
Encoding supports for GNMI

### ISSUE THREAD

**Issue by littlespace** [aristanetworks/goarista#39]
Hi , 

I just wanted to know if Arista supports protobuf as part of the GNMI encoding. I could not find it in your GNMI codes.

Thanks,

**Comment by aaronbee** [comment]
Are you asking about the protobuf encoded values inside gNMI requests and responses as described [here](https://github.com/openconfig/reference/blob/master/rpc/gnmi/protobuf-vals.md)? We do not support that yet.
