### ISSUE TITLE
go get github.com/aristanetworks/goarista/cmd/gnmi failing

### ISSUE THREAD

**Issue by ragagit** [aristanetworks/goarista#44]
Hi 

Getting gnmi with
go get github.com/aristanetworks/goarista/cmd/gnmi
fails with
<img width="786" alt="Screen Shot 2019-07-24 at 3 51 03 PM" src="https://user-images.githubusercontent.com/8247934/61823974-e4ae5300-ae2a-11e9-80cc-8faef0a83d61.png">

protoc --version  is libprotoc 3.7.1

**Comment by aaronbee** [comment]
Your github.com/golang/protobuf/proto dependency is out of date. I believe the following will update all the of `gnmi`'s dependencies for you:

`go get -u github.com/aristanetworks/goarista/cmd/gnmi`

If that doesn't fix it then you can manually update the proto dependency:

`go get -u github.com/golang/protobuf/proto`

And then try to get gnmi again.

**Comment by ragagit** [comment]
Yeah, I tried that a few times but didn't help. What I ended up doing was to get the code and compile gnmi, that works, now I can use the command.Thanks for your prompt reply I appreciate that.
