### ISSUE TITLE
valuelabel doesn't work for non strings

### ISSUE THREAD

**Issue by kalebris** [aristanetworks/goarista#56]
There are a few metrics in openconfig for example bgp asn along the path of 

/network-instances/network-instance\[name=(?P<vrf>.+)\]/protocols/protocol\[identifier=BGP\]\[name=BGP\]/bgp/neighbors/neighbor\[neighbor-address=(?P<neighbor>.+)\]/state/peer-as

where valuelabel would be handy as it is difficult to join prometheus metrics based on values.

**Comment by kalebris** [comment]
Created https://github.com/aristanetworks/goarista/pull/57 to work around this.

**Comment by avi-kumar** [comment]
resolved in https://github.com/aristanetworks/goarista/commit/5051269002d8d1bd096a3bcaccee35eaa50a8b35
