### ISSUE TITLE
-v flag redefined when using with github.com/golang/glog

### ISSUE THREAD

**Issue by biplamal** [aristanetworks/goarista#63]
/tmp/go-build149476797/b001/tests.test flag redefined: v
panic: /tmp/go-build149476797/b001/tests.test flag redefined: v
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00007e180, 0x12ab2f8, 0x1b49c88, 0x1151007, 0x1, 0x116e1e8, 0x14)
        /usr/local/go/src/flag/flag.go:871 +0x485
flag.Var(...)
        /usr/local/go/src/flag/flag.go:886
github.com/golang/glog.init.0()
        /home/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:401 +0x127
Further investigating we discovered that go test module has its own glog module and again goarista package is redefining the same glog module with same flags, which is conflicting and Its expected to fail [go language behavior]

**Comment by aaronbee** [comment]
Commit https://github.com/aristanetworks/goarista/commit/35110c587616aa060483fc4fa4a4cb5a6cdda055 should help. This removes the use of github.com/aristanetworks/glog from our gnmi library, so you can use it with other libraries that depend on github.com/golang/glog.
