### ISSUE TITLE
Update the gnmi installation readme

### ISSUE THREAD

**Issue by DJnet26** [aristanetworks/goarista#66]
Hello,
I think `GO111MODULE=on go get github.com/aristanetworks/goarista/cmd/gnmi` is now obsolete. But the readme still refers to this.
It need to be updated with `GO111MODULE=on go install github.com/aristanetworks/goarista/cmd/gnmi@latest`
Thanks

**Comment by aaronbee** [comment]
The readme has been updated. Thanks for the issue.
